sudo: required
services:
  - docker
script:
  - docker build -t ddydeveloper/angular6-test-app .
after_script:
  - docker images
before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
deploy:
  provider: script
  script: docker push ddydeveloper/angular6-test-app
  on:
    branch: master
after_success:
  — sh .travis/deploy_dockerhub.sh
  — test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
email:
  - ddydeveloper@gmail.com
