sudo: required

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker login -u _ --password=$HEROKU_API_KEY registry.heroku.com

script:
  - docker build -t ddydeveloper/angular6-test-api .
  # - docker tag ddydeveloper/angular6-test-api registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  - provider: script
    script: docker push ddydeveloper/angular6-test-api
    on:
      all_branches: true
  # - provider: script
  #   script: docker push registry.heroku.com/$HEROKU_APP_NAME/web
  #   on:
  #     all_branches: true
  
email:
  - ddydeveloper@gmail.com