sudo: required

services:
  - docker

deploy:
  - provider: script
    script: bash heroku/deploy.sh
    on:
      branch: master
  - provider: script
    script: bash heroku/deploy_dev.sh
    on:
      branch: develop

email:
  - ddydeveloper@gmail.com