sudo: required
services:
  - docker
before_install:
  - sudo snap install --classic heroku
script:
  - docker build -t ddydeveloper/angular6-test-api .
after_script:
  - docker images
before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" registry.heroku.com
  - docker login -u _ -p "$HEROKU_PASS" registry.heroku.com
  - docker tag ddydeveloper/angular6-test-api registry.heroku.com/$HEROKU_APP/web
deploy:
  provider: script
  script:
    docker push ddydeveloper/angular6-test-api;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
  on:
    branch: master
email:
    recipients:
      - ddydeveloper@gmail.com
    on_success: always
    on_failure: always
    
