sudo: required
services:
  - docker
script:
  - docker build -t angular6-test-api .
after_script:
  - docker images
before_deploy:
  - docker login ddydeveloper.azurecr.io -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag angular6-test-api ddydeveloper.azurecr.io/angular6-test-api
deploy:
  provider: script
  script: docker push ddydeveloper.azurecr.io/angular6-test-api
email:
    recipients:
      - ddydeveloper@gmail.com
    on_success: always
    on_failure: always